# -*- coding: utf-8 -*-
"""unidConservacao

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WecBEzbv8XMCm0XL_31zCp14Scrsv3E-

1.   Filtrar dados entre os anos 1999 e 2020
2.  Filtrar estados de interesse
3. Juntar tabelas de unidades federais e estaduais.
"""

import pandas as pd

anos = [1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]
estados = ['Acre', 'Amapá', 'Amazonas', 'Maranhão', 'Mato Grosso', 'Pará', 'Roraima', 'Rondônia', 'Tocantins']
siglas = ['AC', 'AM', 'AP', 'MA', 'MT', 'PA', 'RO', 'RR', 'TO']
index = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
meses = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']

UC_estaduais = 'https://raw.githubusercontent.com/LABSensing/LabSesing-case-study/refs/heads/main/UC%20por%20estado/extensao-de-ucs-estaduais-na-amazonia-legal-por-uf-(area_ano-de-criacao).csv'
UC_federais = 'https://raw.githubusercontent.com/LABSensing/LabSesing-case-study/refs/heads/main/UC%20por%20estado/extensao-de-ucs-federais-na-amazonia-legal-por-uf-(area_ano-de-criacao).csv'

dfestaduais = pd.read_csv(UC_estaduais, sep = ';')
dffederais = pd.read_csv(UC_federais, sep = ';')

dfestaduais.info()

dfestaduais

dfestaduais['Anos'].unique()

dfestaduais_matriz = dfestaduais['Anos'].isin(anos)
estaduais_df = dfestaduais[dfestaduais_matriz]
estaduais_df

"""

---



---


UC federais"""

dffederais.info()

dffederais['Anos'].unique()

dffederais

dffederais.drop(columns = ['BA', 'PI'], inplace = True)
dffederais

dffederais_matriz = dffederais['Anos'].isin(anos)
federais_df = dffederais[dffederais_matriz]
federais_df

"""

---



---


merge dos dois dfs"""

uc_df = estaduais_df.merge(federais_df, on = 'Anos', how = 'outer', suffixes = ('_estadual', '_federal'))
uc_df

uc_df.to_csv('unidConservacao-cleaned', index = False)

"""


---


---
teste 2

juntandos as tabelas pelas colunas de siglas"""

df_federais_teste = federais_df.drop('Anos', axis = 1)
df_federais_teste

uc_df_teste = estaduais_df.merge(df_federais_teste, on = siglas, how = 'outer')
uc_df_teste